# change the followings to match your Github username and repo name
baseurl: "/tailpages" # the name of your github repo
url: "https://blog.wesselvandergoot.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Wessel van der Goot"
#description: A Github Pages (Jekyll) website based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Wessel van der Goot
author-bio: Test  # change to false to hide
author-image: 279.png  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Bitcoin
  permalink: bitcoin
- text: Blog
  permalink: blog

# use false to turn off any social media links
linkedin: https://www.linkedin.com/in/wessel-van-der-goot
twitter: https://twitter.com/wvdgoot
github: https://github.com/wvdgoot
email: me[at]wesselvandergoot[dot]com
facebook: false
instagram: false
medium: false
google-scholar: false

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
